# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "AnsonHe"
repo_name: "adversarial-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 300

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
json_readme_path: './docs/adversarial-arxiv-daily.json'
json_gitpage_path: './docs/adversarial-arxiv-daily-web.json'
json_wechat_path: './docs/adversarial-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Adversarial attacks":
        filters: ["Adversarial attacks", "Adversarial examples"]
    "Poisoning attacks":
        filters: ["Poisoning attacks", "Unlearnable examples", "Backdoor attacks", "Data poisoning"]
    "Generative models safety":
        filters: ["LLM safety", "AIGC safety", "Diffusion models safety", "Generative models safety"]
    "Data privacy":
        filters: ["Data privacy"]
    "Model Privacy":
        filters: ["Model Privacy"]
    "Forensics":
        filters: ["AI Forensics", "Deepfake"]
    "AIGC":
        filters: ["Generative models","AIGC","LLM"]
